var date = new Date("2021/01/02");

module.exports = [{
  url: "/2018/02/advanced-nodejs.html",
  title: "おすすめのAV女優",
  image: "/image/sample.jpg",
  subtitle1: "好きな人は",
  subtitle2: "ココなら",
  subtitle3: "体",
  subtitle4: "フェイスブック",
  subtitle5: "だけ",
  subcontent: "node.jsのが概要について調べていきましょう。これからはどのようにプログラムをしていくのでしょう",
  content1: "Node.js で Excel ファイルが触れるなんて！！",
  content2: "Node.js で Excel ファイルが触れるなんて！！",
  content3: "Node.js で Excel ファイルが触れるなんて！！",
  content4: "Node.js で Excel ファイルが触れるなんて！！",
  content5: "Node.js で Excel ファイルが触れるなんて！！",
  content6: "Node.js で Excel ファイルが触れるなんて！！",
  authors: ["Yuta Sato"],
  createdAt: date,
  updatedAt: date
}, {
  url: "/2018/03/advanced-nodejs.html",
  title: "configration",
  image: "/image/sample.jpg",
  subtitle1: "korakara",
  subtitle2: "korakara",
  subtitle3: "korakara",
  subtitle4: "korakara",
  subtitle5: "korakara",
  subcontent: "node.jsのが概要について調べていきましょう。これからはどのようにプログラムをしていくのでしょう",
  content1: "Node.js で Excel ファイルが触れるなんて！！",
  content2: "Node.js で Excel ファイルが触れるなんて！！",
  content3: "Node.js で Excel ファイルが触れるなんて！！",
  content4: "Node.js で Excel ファイルが触れるなんて！！",
  content5: "Node.js で Excel ファイルが触れるなんて！！",
  content6: "Node.js で Excel ファイルが触れるなんて！！",
  authors: ["Yuta Sato"],
  createdAt: date,
  updatedAt: date
}, {
  url: "/2018/04/advanced-nodejs.html",
  title: "チョコ",
  image: "/image/sample.jpg",
  subtitle1: "korakara",
  subtitle2: "korakara",
  subtitle3: "korakara",
  subtitle4: "korakara",
  subtitle5: "korakara",
  subcontent: "node.jsのが概要について調べていきましょう。これからはどのようにプログラムをしていくのでしょう",
  content1: "Node.js で Excel ファイルが触れるなんて！！",
  content2: "Node.js で Excel ファイルが触れるなんて！！",
  content3: "Node.js で Excel ファイルが触れるなんて！！",
  content4: "Node.js で Excel ファイルが触れるなんて！！",
  content5: "Node.js で Excel ファイルが触れるなんて！！",
  content6: "Node.js で Excel ファイルが触れるなんて！！",
  authors: ["Yuta Sato"],
  createdAt: date,
  updatedAt: date
}, {
  url: "/2018/04/advanced-nodejs.html",
  title: "チョコレート",
  image: "/image/sample.jpg",
  subtitle1: "korakara",
  subtitle2: "korakara",
  subtitle3: "korakara",
  subtitle4: "korakara",
  subtitle5: "korakara",
  subcontent: "node.jsのが概要について調べていきましょう。これからはどのようにプログラムをしていくのでしょう",
  content1: "Node.js で Excel ファイルが触れるなんて！！",
  content2: "Node.js で Excel ファイルが触れるなんて！！",
  content3: "Node.js で Excel ファイルが触れるなんて！！",
  content4: "Node.js で Excel ファイルが触れるなんて！！",
  content5: "Node.js で Excel ファイルが触れるなんて！！",
  content6: "Node.js で Excel ファイルが触れるなんて！！",
  authors: ["Yuta Sato"],
  createdAt: date,
  updatedAt: date
}, {
  url: "/2018/04/advanced-nodejs.html",
  title: "amangus",
  image: "/image/sample.jpg",
  subtitle1: "korakara",
  subtitle2: "korakara",
  subtitle3: "korakara",
  subtitle4: "korakara",
  subtitle5: "korakara",
  subcontent: "node.jsのが概要について調べていきましょう。これからはどのようにプログラムをしていくのでしょう",
  content1: "Node.js で Excel ファイルが触れるなんて！！",
  content2: "Node.js で Excel ファイルが触れるなんて！！",
  content3: "Node.js で Excel ファイルが触れるなんて！！",
  content4: "Node.js で Excel ファイルが触れるなんて！！",
  content5: "Node.js で Excel ファイルが触れるなんて！！",
  content6: "Node.js で Excel ファイルが触れるなんて！！",
  authors: ["Yuta Sato"],
  createdAt: date,
  updatedAt: date
}, {
  url: "/2018/04/advanced-nodejs.html",
  title: "チョコ",
  image: "/image/sample.jpg",
  subtitle1: "korakara",
  subtitle2: "korakara",
  subtitle3: "korakara",
  subtitle4: "korakara",
  subtitle5: "korakara",
  subcontent: "node.jsのが概要について調べていきましょう。これからはどのようにプログラムをしていくのでしょう",
  content1: "Node.js で Excel ファイルが触れるなんて！！",
  content2: "Node.js で Excel ファイルが触れるなんて！！",
  content3: "Node.js で Excel ファイルが触れるなんて！！",
  content4: "Node.js で Excel ファイルが触れるなんて！！",
  content5: "Node.js で Excel ファイルが触れるなんて！！",
  content6: "Node.js で Excel ファイルが触れるなんて！！",
  authors: ["Yuta Sato"],
  createdAt: date,
  updatedAt: date
}, {
  url: "/2018/04/advanced-nodejs.html",
  title: "node",
  image: "/image/sample.jpg",
  subtitle1: "korakara",
  subtitle2: "korakara",
  subtitle3: "korakara",
  subtitle4: "korakara",
  subtitle5: "korakara",
  subcontent: "node.jsのが概要について調べていきましょう。これからはどのようにプログラムをしていくのでしょう",
  content1: "Node.js で Excel ファイルが触れるなんて！！",
  content2: "Node.js で Excel ファイルが触れるなんて！！",
  content3: "Node.js で Excel ファイルが触れるなんて！！",
  content4: "Node.js で Excel ファイルが触れるなんて！！",
  content5: "Node.js で Excel ファイルが触れるなんて！！",
  content6: "Node.js で Excel ファイルが触れるなんて！！",
  authors: ["Yuta Sato"],
  createdAt: date,
  updatedAt: date
}, {
  url: "/2018/04/advanced-nodejs.html",
  title: "Node.js 応用",
  image: "/image/sample.jpg",
  subtitle1: "korakara",
  subtitle2: "korakara",
  subtitle3: "korakara",
  subtitle4: "korakara",
  subtitle5: "korakara",
  subcontent: "node.jsのが概要について調べていきましょう。これからはどのようにプログラムをしていくのでしょう",
  content1: "Node.js で Excel ファイルが触れるなんて！！",
  content2: "Node.js で Excel ファイルが触れるなんて！！",
  content3: "Node.js で Excel ファイルが触れるなんて！！",
  content4: "Node.js で Excel ファイルが触れるなんて！！",
  content5: "Node.js で Excel ファイルが触れるなんて！！",
  content6: "Node.js で Excel ファイルが触れるなんて！！",
  authors: ["Yuta Sato"],
  createdAt: date,
  updatedAt: date
}]
